run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/G20-00/task-management-service-go
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - ptrToRefParam
      - exitAfterDefer
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016"]

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - goimports
    - gocritic
    - revive
    - stylecheck
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - typecheck
  
  disable:
    - depguard

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
